### ISSUE TITLE
greedy_related -h not working

### ISSUE THREAD

**Issue by C-Gouveia** [choishingwan/GreedyRelated#3]
Hi! Thanks for sharing this!

I'm trying to use your tool but when I type the command greedy_related -h nothing happens... Any idea why?

I did this before:
g++ -std=c++11 main.cpp misc.cpp -o greedy_related 
(with no output)

Thanks,
Catarina

**Comment by choishingwan** [comment]
Sorry, wasn't paying attention to this repo. 

you should type `./greedy_related -h` 

Will transfer this repo to https://gitlab.com/choishingwan/GreedyRelated

and maybe I will update the Read me once I finished that.
